EjercicioPractico/Controllers/ProspectoController.cs
using EjercicioPractico.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EjercicioPractico.Controllers
{
    public class ProspectoController : Controller
    {
        // GET: Prospecto
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Listar()
        {
            EjemploProspectosContex db = new EjemploProspectosContex();
            List<Prospecto> lista = db.Prospecto.ToList();
            return View(lista);
        }

        public ActionResult Revisar()
        {
            using (EjemploProspectosContex db = new EjemploProspectosContex())
            {
                List<Prospecto> lista = db.Prospecto.ToList();
                return View(lista);
            }
        }
        public ActionResult Agregar()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Agregar(Prospecto A, HttpPostedFileBase[] Formulario, string[] NomArchivo)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }
            try
            {
                using (EjemploProspectosContex db = new EjemploProspectosContex())
                {
                    A.pros_rutas = "";
                    A.pros_notas = "";
                    A.pros_estatus = "Enviado";
                    db.Prospecto.Add(A);
                    db.SaveChanges();
                    string Rutas = "";
                    if (Formulario != null&& NomArchivo!=null)
                    {


                        for (int i = 0; i < Formulario.Length; i++)
                        {
                            if (Formulario[i] != null && Formulario[i].ContentLength > 0)
                            {
                                var fileName = A.pros_id + "_" + NomArchivo[i] + ".pdf";
                                Rutas += fileName + ";";
                                // extract only the fielname

                                // store the file inside ~/App_Data/uploads folder
                                var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);
                                Formulario[i].SaveAs(path);
                            }
                        }
                    }
                    A.pros_rutas = Rutas;
                    db.SaveChanges();
                    return View();
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("Error al agregar", ex);
                return View();
            }

        }
        [HttpPost]
        public ActionResult ConsultaDetalles(int id)
        {
            try
            {


                using (EjemploProspectosContex db = new EjemploProspectosContex())
                {
                    var detalles = db.Prospecto.Find(id);
                    return PartialView("_FormularioView", detalles);
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }
        public ActionResult ConsultaRevision(int id)
        {
            try
            {
                using (EjemploProspectosContex db = new EjemploProspectosContex())
                {
                    var detalles = db.Prospecto.Find(id);
                    return PartialView("_RevisionView", detalles);
                }
            }
            catch (Exception ex)
            {
                return View(ex);
            }
        }
        public JsonResult Aprovar(int id, string notas)
        {
            if (notas == null || notas == "")
            {
                notas = " ";
            }
            try
            {
                using (EjemploProspectosContex db = new EjemploProspectosContex())
                {
                    var Prospecto = db.Prospecto.Find(id);
                    Prospecto.pros_notas = notas;
                    Prospecto.pros_estatus = "Autorizado";
                    db.SaveChanges();
                    return Json("Exito", JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult Rechazar(int id, string notas)
        {
            if (notas == null || notas == "")
            {
                notas = " ";
            }
            try
            {
                using (EjemploProspectosContex db = new EjemploProspectosContex())
                {
                    var Prospecto = db.Prospecto.Find(id);
                    Prospecto.pros_notas = notas;
                    Prospecto.pros_estatus = "Rechazado";
                    db.SaveChanges();
                    return Json("Exito", JsonRequestBehavior.AllowGet);
                }
            }
            catch (Exception ex)
            {
                return Json("Error", JsonRequestBehavior.AllowGet);
            }
        }
        public FileResult GetReport(string path)
        {
            var FileURL = Path.Combine(Server.MapPath("~/App_Data/uploads"), path);
            string ReportURL = path;
            byte[] FileBytes = System.IO.File.ReadAllBytes(FileURL);
            return File(FileBytes, "application/pdf");
        }
    }

}

EjercicioPractico/Views/Shared/_FormularioView.cshtml
@model EjercicioPractico.Models.Prospecto
<div class="form-horizontal">
    <h2>Detalles</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        @Html.LabelFor(model => model.pros_nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-75">
            @Html.EditorFor(model => model.pros_nombre, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.pros_nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        @Html.LabelFor(model => model.pros_apellidoP, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-75">
            @Html.EditorFor(model => model.pros_apellidoP, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.pros_apellidoP, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        @Html.LabelFor(model => model.pros_apellidoM, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-75">
            @Html.EditorFor(model => model.pros_apellidoM, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.pros_apellidoM, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        @Html.LabelFor(model => model.pros_calle, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-75">
            @Html.EditorFor(model => model.pros_calle, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.pros_calle, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        @Html.LabelFor(model => model.pros_num, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-75">
            @Html.EditorFor(model => model.pros_num, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.pros_num, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        @Html.LabelFor(model => model.pros_colonia, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-75">
            @Html.EditorFor(model => model.pros_colonia, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.pros_colonia, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        @Html.LabelFor(model => model.pros_cp, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-75">
            @Html.EditorFor(model => model.pros_cp, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.pros_cp, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        @Html.LabelFor(model => model.pros_tel, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-75">
            @Html.EditorFor(model => model.pros_tel, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.pros_tel, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="row">
        @Html.LabelFor(model => model.pros_rfc, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-75">
            @Html.EditorFor(model => model.pros_rfc, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            @Html.ValidationMessageFor(model => model.pros_rfc, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row">
        @Html.LabelFor(model => model.pros_estatus, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-75">
            @Html.EditorFor(model => model.pros_estatus, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>
    <div class="row">
        @Html.LabelFor(model => model.pros_notas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-75">
            @Html.TextAreaFor(model => model.pros_notas, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
        </div>
    </div>

    <div class="row" id="Archivos">
        <label>Archivos</label>
        <div class="col-75">

            @{
                string Documentos = Model.pros_rutas;
                string[] RutasDoc = Documentos.Split(';');

                foreach (var Ruta in RutasDoc)
                {
                    if (Ruta != null && Ruta != "")
                    {
                        <div class="row">
                            @Html.ActionLink(Ruta, "GetReport", "Prospecto", new { path = Ruta }, new { target = "_blank" })
                        </div>
                    }

                }
            }
        </div>
    </div>
    <br />
</div>

EjercicioPractico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Ejercicio ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="topnav">
        @Html.ActionLink("Inicio", "Index", "Home")
        @Html.ActionLink("Listar", "Listar", "Prospecto")
        @Html.ActionLink("Agregar", "Agregar", "Prospecto")
        @Html.ActionLink("Evaluar", "Revisar", "Prospecto")
    </div>
    <div class="container body-content">
        @RenderBody()
        
        <footer>
            <p>&copy; @DateTime.Now.Year - Ejercicio ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

EjercicioPractico/Views/Shared/_RevisionView.cshtml
@model EjercicioPractico.Models.Prospecto
<form method="post">
    <div class="form-horizontal">
        <h2>Detalles Revision</h2>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="row">
            @Html.LabelFor(model => model.pros_nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-75">
                @Html.EditorFor(model => model.pros_nombre, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.pros_nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(model => model.pros_apellidoP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-75">
                @Html.EditorFor(model => model.pros_apellidoP, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.pros_apellidoP, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(model => model.pros_apellidoM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-75">
                @Html.EditorFor(model => model.pros_apellidoM, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.pros_apellidoM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(model => model.pros_calle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-75">
                @Html.EditorFor(model => model.pros_calle, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.pros_calle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(model => model.pros_num, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-75">
                @Html.EditorFor(model => model.pros_num, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.pros_num, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(model => model.pros_colonia, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-75">
                @Html.EditorFor(model => model.pros_colonia, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.pros_colonia, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(model => model.pros_cp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-75">
                @Html.EditorFor(model => model.pros_cp, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.pros_cp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(model => model.pros_tel, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-75">
                @Html.EditorFor(model => model.pros_tel, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.pros_tel, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="row">
            @Html.LabelFor(model => model.pros_rfc, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-75">
                @Html.EditorFor(model => model.pros_rfc, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                @Html.ValidationMessageFor(model => model.pros_rfc, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="row">
            @Html.LabelFor(model => model.pros_estatus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-75">
                @Html.EditorFor(model => model.pros_estatus, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
            </div>
        </div>
        <div class="row">
            @Html.LabelFor(model => model.pros_notas, htmlAttributes: new { @class = "control-label col-md-2", id = "notas" })
            <div class="col-75">
                @Html.TextAreaFor(model => model.pros_notas, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="row" id="Archivos">
            <label>Archivos</label>
            <div class="col-75">
                @{
                    string Documentos = Model.pros_rutas;
                    string[] RutasDoc = Documentos.Split(';');

                    foreach (var Ruta in RutasDoc)
                    {
                        if (Ruta != null && Ruta != "")
                        {
                            <div class="row">
                                @Html.ActionLink(Ruta, "GetReport", "Prospecto", new { path = Ruta }, new { target = "_blank" })
                            </div>
                        }

                    }
                }
            </div>
        </div>
        <br><br>
        <div class="row">
            Acción
            <div class="col-75">
                <button type="button" onclick="Aprovar(@Model.pros_id)" class="btnC">Autorizar</button>
                <button type="button" onclick="Rechazar(@Model.pros_id)" class="btnCRed">Rechazar</button>
            </div>
        </div>
        <br /><br />
    </div>
</form>